#!/bin/bash
# This script displays information about subdomains

# Define a function to get the record type and destination of a subdomain
get_info () {
    # Use dig command to query the DNS records of the subdomain
    # Use awk to filter and format the output
    dig $1 +short | awk 'NR==1 {dest=$0} END {type="A"; if (dest ~ /:/) type="AAAA"; printf "The subdomain %s is a %s record and points to %s\n", $1, type, dest}'
}

# Check the number of arguments
if [ $# -eq 0 ]; then
    # No arguments provided, print usage and exit
    echo "Usage: $0 domain [subdomain]"
    exit 1
elif [ $# -eq 1 ]; then
    # Only domain argument provided, display information for default subdomains
    domain=$1
    get_info "www.$domain"
    get_info "lb-01.$domain"
    get_info "web-01.$domain"
    get_info "web-02.$domain"
elif [ $# -eq 2 ]; then
    # Domain and subdomain arguments provided, display information for the specified subdomain
    domain=$1
    subdomain=$2
    get_info "$subdomain.$domain"
else
    # Too many arguments provided, print usage and exit
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi
